version: '3'

services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - db-data:/var/lib/postgresql/data

  zookeeper1:
    image: bitnami/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper

  kafka1:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_CREATE_TOPIC: "usuarios:1:3"
    depends_on:
      - zookeeper1

volumes:
  db-data:
